### ISSUE TITLE
Panic when target pod is not specified

### ISSUE THREAD

**Issue by aylei** [aylei/kubectl-debug#17]
```bash
➜  kubectl-debug git:(master) ✗ kubectl debug
error pod not specified
pod name must be specified
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x1b9a7c2]

goroutine 1 [running]:
github.com/aylei/kubectl-debug/pkg/plugin.(*DebugOptions).Run(0xc0002481c0, 0x0, 0x0)
	/Users/alei/go/src/github.com/aylei/kubectl-debug/pkg/plugin/cmd.go:201 +0x62
github.com/aylei/kubectl-debug/pkg/plugin.NewDebugCmd.func1(0xc00034f400, 0x2bad698, 0x0, 0x0)
	/Users/alei/go/src/github.com/aylei/kubectl-debug/pkg/plugin/cmd.go:100 +0x134
github.com/aylei/kubectl-debug/vendor/github.com/spf13/cobra.(*Command).execute(0xc00034f400, 0xc0000b8190, 0x0, 0x0, 0xc00034f400, 0xc0000b8190)
	/Users/alei/go/src/github.com/aylei/kubectl-debug/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/aylei/kubectl-debug/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00034f400, 0x2080880, 0x1d54140, 0x207c238)
	/Users/alei/go/src/github.com/aylei/kubectl-debug/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/aylei/kubectl-debug/vendor/github.com/spf13/cobra.(*Command).Execute(0xc00034f400, 0xc0000ce000, 0x2088300)
	/Users/alei/go/src/github.com/aylei/kubectl-debug/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/Users/alei/go/src/github.com/aylei/kubectl-debug/cmd/plugin/main.go:17 +0x10e
```

**Comment by aylei** [comment]
closed via https://github.com/aylei/kubectl-debug/commit/76b1bfce786ccdffc5aa1b5fea0b1cdcc5a35c87
