### ISSUE TITLE
Panic when exit the debug container

### ISSUE THREAD

**Issue by shafreeck** [aylei/kubectl-debug#41]
```
Start deleting agent pod tidb-pd-2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10c9a57]

goroutine 1 [running]:
fmt.Fprintf(0x0, 0x0, 0x20b845f, 0x4e, 0xc0008297f0, 0x2, 0x2, 0x25, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.4/libexec/src/fmt/print.go:200 +0x77
github.com/aylei/kubectl-debug/pkg/plugin.(*DebugOptions).Run.func2.1()
        /Users/alei/go/src/github.com/aylei/kubectl-debug/pkg/plugin/cmd.go:472 +0x2c9
k8s.io/kubernetes/pkg/util/interrupt.(*Handler).Close.func1()
        /Users/alei/go/pkg/mod/k8s.io/kubernetes@v1.13.1/pkg/util/interrupt/interrupt.go:65 +0x46
sync.(*Once).Do(0xc0000c74c0, 0xc000829888)
        /usr/local/Cellar/go/1.12.4/libexec/src/sync/once.go:44 +0xb3
k8s.io/kubernetes/pkg/util/interrupt.(*Handler).Close(0xc0000c74a0)
        /Users/alei/go/pkg/mod/k8s.io/kubernetes@v1.13.1/pkg/util/interrupt/interrupt.go:63 +0x54
k8s.io/kubernetes/pkg/util/interrupt.(*Handler).Run(0xc0000c74a0, 0xc0000ac180, 0x0, 0x0)
        /Users/alei/go/pkg/mod/k8s.io/kubernetes@v1.13.1/pkg/util/interrupt/interrupt.go:103 +0x113
github.com/aylei/kubectl-debug/pkg/plugin.(*DebugOptions).Run.func2(0xc000000008, 0x20fac30)
        /Users/alei/go/src/github.com/aylei/kubectl-debug/pkg/plugin/cmd.go:475 +0xf3
k8s.io/kubernetes/pkg/util/interrupt.(*Handler).Run(0xc0000c7470, 0xc0000c7440, 0x0, 0x0)
        /Users/alei/go/pkg/mod/k8s.io/kubernetes@v1.13.1/pkg/util/interrupt/interrupt.go:103 +0xff
github.com/aylei/kubectl-debug/pkg/util.TTY.Safe(0x2244600, 0xc0000b4000, 0x2244620, 0xc0000b8000, 0x1, 0x0, 0xc00013e780, 0xc0000c7440, 0x0, 0x0)
        /Users/alei/go/src/github.com/aylei/kubectl-debug/pkg/util/term.go:110 +0x189
github.com/aylei/kubectl-debug/pkg/plugin.(*DebugOptions).Run(0xc000174700, 0x0, 0x20fac28)
        /Users/alei/go/src/github.com/aylei/kubectl-debug/pkg/plugin/cmd.go:478 +0x8ea
github.com/aylei/kubectl-debug/pkg/plugin.NewDebugCmd.func1(0xc000551180, 0xc0000bb2c0, 0x1, 0x6)
        /Users/alei/go/src/github.com/aylei/kubectl-debug/pkg/plugin/cmd.go:150 +0xe7
github.com/spf13/cobra.(*Command).execute(0xc000551180, 0xc00003a080, 0x6, 0x6, 0xc000551180, 0xc00003a080)
        /Users/alei/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc000551180, 0xc0000b4000, 0x2244620, 0xc0000b8000)
        /Users/alei/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/alei/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
        /Users/alei/go/src/github.com/aylei/kubectl-debug/cmd/plugin/main.go:17 +0x110
```

**Comment by aylei** [comment]
Look like the same problem with #38 

Could you please check if the you have the permission for deleting pods? (`kubectl auth can-i delete pod`)

**Comment by shafreeck** [comment]
I have permission, and it does not occur later. I don't know why. It is not a problem for me, I'll close this issue.
